<?xml version="1.0" encoding="utf-8"?><Database Name="QL_CAFE" Class="QLCAFEDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MSI\SQLEXPRESS;Initial Catalog=QL_CAFE;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="QL_CAFEConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETHOADON" Member="CHITIETHOADONs">
    <Type Name="CHITIETHOADON">
      <Column Name="MAHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAMH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" />
      <Association Name="MATHANG_CHITIETHOADON" Member="MATHANG" ThisKey="MAMH" OtherKey="MAMH" Type="MATHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VAITRO" Member="VAITROs">
    <Type Name="VAITRO">
      <Column Name="MAVT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENVT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="VAITRO_NHANVIEN" Member="NHANVIENs" ThisKey="MAVT" OtherKey="MAVT" Type="NHANVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MAHD" OtherKey="MAHD" Type="CHITIETHOADON" />
      <Association Name="NHANVIEN_HOADON" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAISANPHAM" Member="LOAISANPHAMs">
    <Type Name="LOAISANPHAM">
      <Column Name="MALOAI" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LOAISANPHAM_MATHANG" Member="MATHANGs" ThisKey="MALOAI" OtherKey="MALOAI" Type="MATHANG" />
    </Type>
  </Table>
  <Table Name="dbo.MATHANG" Member="MATHANGs">
    <Type Name="MATHANG">
      <Column Name="MAMH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENMH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ANH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MALOAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MANL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MATHANG_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MAMH" OtherKey="MAMH" Type="CHITIETHOADON" />
      <Association Name="LOAISANPHAM_MATHANG" Member="LOAISANPHAM" ThisKey="MALOAI" OtherKey="MALOAI" Type="LOAISANPHAM" IsForeignKey="true" />
      <Association Name="NGUYENLIEU_MATHANG" Member="NGUYENLIEU" ThisKey="MANL" OtherKey="MANL" Type="NGUYENLIEU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NGUYENLIEU" Member="NGUYENLIEUs">
    <Type Name="NGUYENLIEU">
      <Column Name="MANL" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENNL" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MANCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CAPNHATNGAY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="NGUYENLIEU_MATHANG" Member="MATHANGs" ThisKey="MANL" OtherKey="MANL" Type="MATHANG" />
      <Association Name="NHACUNGCAP_NGUYENLIEU" Member="NHACUNGCAP" ThisKey="MANCC" OtherKey="MANCC" Type="NHACUNGCAP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHACUNGCAP" Member="NHACUNGCAPs">
    <Type Name="NHACUNGCAP">
      <Column Name="MANCC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="NHACUNGCAP_NGUYENLIEU" Member="NGUYENLIEUs" ThisKey="MANCC" OtherKey="MANCC" Type="NGUYENLIEU" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="TENDANGNHAP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MAVT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NHANVIEN_HOADON" Member="HOADONs" ThisKey="MANV" OtherKey="MANV" Type="HOADON" />
      <Association Name="VAITRO_NHANVIEN" Member="VAITRO" ThisKey="MAVT" OtherKey="MAVT" Type="VAITRO" IsForeignKey="true" />
    </Type>
  </Table>
</Database>